
GET http://localhost:8000/calcular?num1=1&num2=2&op=/

### POST request to localhost
POST http://localhost:8000/calc
Content-Type: application/json

{
    "num1": "1",
    "num2": "1",
    "op" : "+"
}